# Generated by Django 5.2.3 on 2025-07-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-avatar.png', upload_to='profile_images/'),
        ),
    ]
