# Generated by Django 5.2.3 on 2025-07-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default-avatar.png', upload_to='profile_images/'),
        ),
    ]
