# Generated by Django 5.2.3 on 2025-07-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
